### ISSUE TITLE
Section 0 title not displayed

### ISSUE THREAD

**Issue by rolandsherwood2** [cellule-tice/moodle-format_collapsibletopics#1]
Many thanks for sharing this excellent plugin. One quick question: both this and the collapsibleweeks format force the title of section 0 to be hidden (except when in editing mode). Is there a particular reason for this? If it's purely for aesthetic reasons, I wonder if you might consider including a setting which would allow admins to choose whether the section 0 title is hidden or not? Thanks again.

**Comment by jondo** [comment]
Can this be closed as fixed?
