### ISSUE TITLE
Using the Collapsible Topics in an Right-to-left environment

### ISSUE THREAD

**Issue by acquaalta** [cellule-tice/moodle-format_collapsibletopics#10]
Hi,

When using the collapsed topics format in an Right-to-left environment, the icon of the collapse/expand button of a topic is expected to point to the left, since in a Left-to-right environment it points to the right. However, it points to the right in both environments.

Is it something that could be fixed by you? implementing a mechanism that would switch the arrow direction based on the environment UI?

Thanks in advance.

![Collapsed Topics format - LTR vs RTL](https://user-images.githubusercontent.com/51836675/61325618-d0ac9500-a81d-11e9-8eb2-331235abfc82.png)

**Comment by jrm-unamur** [comment]
Hi,
If it is just a problem of icon direction, you can simply add the following rule in styles.css file
```
body.dir-rtl .course-content ul.collapsibletopics a.sectiontoggle[aria-expanded="false"] {
    background-image: url([[pix:moodle|t/collapsed_rtl]]);
}
```
If that is ok for you I will integrate it in the next release
Keep me posted
Cheers

**Comment by acquaalta** [comment]
Hi,
Thank you very much for adding this fix to the official version of the plugin. And I'm sorry for not replying earlier.

Cheers :-)
