### ISSUE TITLE
JS error when using Fordson Integration in Chrome

### ISSUE THREAD

**Issue by tonyyeb** [cellule-tice/moodle-format_collapsibletopics#21]
Hi

We have an issue where if the collapsible topics format integration is switched on in Fordson and a course is viewed in Chrome, this error appears in the console and the expanding/collapsing doesn't work. Firefox works fine:

first.js:489 Uncaught TypeError: Cannot read property 'querySelectorAll' of null at a.value (first.js:489)
at new a (first.js:489)
at HTMLDivElement.<anonymous> (first.js:489)
at Function.each (jquery-3.4.1.min.js:2)
at k.fn.init.each (jquery-3.4.1.min.js:2)
at k.fn.init.value [as collapse] (first.js:489)
at HTMLDivElement.<anonymous> (first.js:489)
at Function.each (jquery-3.4.1.min.js:2)
at k.fn.init.each (jquery-3.4.1.min.js:2)
at HTMLAnchorElement.<anonymous> (first.js:489)

Moodle 3.8.3 (Build: 20200511)
Moodle 3.8 Fordson v3.8 release 1.3 2020030200
format_collapsibletopics 3.9 2020061700

**Comment by jrm-unamur** [comment]
Hi, 
Do you notice the same behaviour when using the course format without the fordson integration?

**Comment by tonyyeb** [comment]
Once it the integration option is turned off, the topics/sections expand and collapse fine.

**Comment by jrm-unamur** [comment]
So I think the problem comes from the integration into fordson theme, I'll have a look tomorrow and will notice Kris (the fordson theme developer). He has probably not ported last developments of the course format into his integration

**Comment by jrm-unamur** [comment]
Apparently Fordson has now ported last developments
