### ISSUE TITLE
Topics cannot expand when using Lamda theme

### ISSUE THREAD

**Issue by EiffelD** [cellule-tice/moodle-format_collapsibletopics#22]
Hi there, thanks for creating this plugin, our team asked for this to be installed on our Moodle 3.9 which has the Lamda theme installed. We noticed the Topics are collapsed and are not able to expand. We also noticed the add activity/resource options are not visible either. 

When switching to the Boost theme, the plugin works as expected and the activity/resource buttons are there as well. How can this be fixed in Lamda?

**Comment by jrm-unamur** [comment]
I guess your theme overrides rendering functions dedicated to topics display. You can compare the generated html for section headers from boost and your theme. If the html is different, the javascript functions dedicated to section collapsing are not called and therefore the plugin cannot work with your theme.
Maybe you can report this issue to the theme developers.
Regards
