### ISSUE TITLE
Restricting access to a topic completely hides it from students despite eye icon not being crossed

### ISSUE THREAD

**Issue by pkgh** [cellule-tice/moodle-format_collapsibletopics#5]
Scenario:
1. Add e.g. a group based restriction to a topic.
2. Keep the eye open, which should keep the section title visible to students in greyed-out format (cf. core Topics / Weekly format)
Cf screenshot
![2018-11-04 22_15_36 - edit 4 final test - mozilla firefox](https://user-images.githubusercontent.com/6607293/47969967-739df400-e07f-11e8-8cc4-463b5ff54b9c.png)

Unfortunately in the Collapsible Topics (as well as Collapsible Weeks) format, setting a section like this completely removes the topic from the Student's course page - which should ONLY happen if that restrict access eye is closed, i.e. has a line running through it.
This is a major weakness of this otherwise very useful & clean course format.

**Comment by jrm-unamur** [comment]
Hi pkgh,
Sorry for late answer, I'm only noticing your post now ... Can you tell me your moodle version and theme (+version) used so that I can replicate the problem that doesn't happen with my boost child theme

**Comment by pkgh** [comment]
Hi,

Collapsible Topics:
1.1-stable 2018061400

Moodle:
3.5.2 (Build: 20180910)
(My production site, which I cannot upgrade most likely until the summer. Have NOT tested higher than that so far.)

Theme:
Boost

Thanks!

**Comment by jrm-unamur** [comment]
Update released! Closing
Cheers
