### ISSUE TITLE
Floating box

### ISSUE THREAD

**Issue by hebertpxx** [cellule-tice/moodle-format_collapsibletopics#6]
There is a problem in the form of Moodle Plugin Collectable Topics, it cuts the floating box (id = action-menu) of activity and resource editing options when editing the course page.

![1](https://user-images.githubusercontent.com/33330466/49151387-e739c680-f2f6-11e8-876f-339f6ca3b3e3.png)

![image](https://user-images.githubusercontent.com/33330466/49151348-cec9ac00-f2f6-11e8-85cf-f0938a3325e6.png)

**Comment by jrm-unamur** [comment]
Hi Herbert,
Can you give me your moodle version and theme (+ version) since I cannot reproduce with my boost child theme

**Comment by chadberg** [comment]
Seeing the same with More theme. It looks to be the CSS defining .collapse to have overflow:hidden;

**Comment by cellule-tice** [comment]
Hi,
format_collapsibletopics doesn't support legacy themes anymore, sorry

**Comment by hebertpxx** [comment]
The Moodle version is 3.5.1
The theme is bought, it calls Academic.

**Comment by cellule-tice** [comment]
If Academic is based on a legacy theme (i.e bootstrapbase), format_collapsibletopics doesn't support it.
