### ISSUE TITLE
Compatibility with Fordson

### ISSUE THREAD

**Issue by dbnschools** [cellule-tice/moodle-format_collapsibletopics#9]
I edited my previous post.  It might have been pre-mature.  While the styling inherits nicely there is more work to be done when editing is turned on.  Please delete or archive.  Not quite ready.

**Comment by jrm-unamur** [comment]
What styling do you want to inherit exactly. I tried your proposed modifications and don't see many display changes whatever the theme used...

**Comment by dbnschools** [comment]
We were testing this plugin to see about using it with the Fordson theme with Moodle 3.6.1.  We are comparing a couple of course formats which might be beneficial for a set of K-12 schools that we support. 
It was a bit early in my looking into your course format to try and get the default course topic styling to apply to your course format.  Some of the structure is different than the core layout.  I like that your course format is very similar to core but just adds what is needed to show and hide topics.  This makes things very simple for teachers.
